import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/Components/Nav";
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Nav />
      <body className={inter.className}>
        <div className="center-max-width">
          <div className="content-container">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
